### Registrar un usuario
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
  "nombre": "Lola",
  "email": "lola@example.com",
  "contrasenia": "lola",
  "rol": "Camarero"
}

###
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
    "nombre": "ana",
    "email": "ana@gmail.com",
    "contrasenia": "ana",
    "rol": "Administrador"
}

###
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
    "nombre": "pepe",
    "email": "pepe@gmail.com",
    "contrasenia": "pepe",
    "rol": ""
}

### Iniciar sesión con usuario normal
POST http://localhost:8000/api/login.php
Content-Type: application/json

{
  
    "email": "lola@example.com",
    "contrasenia": "lola"
    
}

### Iniciar sesión con Administrador
POST http://localhost:8000/api/login.php
Content-Type: application/json

{
  
    "email": "ana@gmail.com",
    "contrasenia": "ana"
    
}

// pruebas para pedido
### Obtener pedidos del usuario autenticado
GET http://localhost:8000/api/pedidos1.php
Content-Type: application/json

### Crear un nuevo pedido,
POST http://localhost:8000/api/pedidos1.php
Content-Type: application/json

{
    "productos": [
        { "id_producto": 1, "cantidad": 2 },
        { "id_producto": 3, "cantidad": 1 }
    ]
}

### Crear un nuevo pedido,
POST http://localhost:8000/api/pedidos1.php
Content-Type: application/json

{

    "productos": [
        { "id_producto": 1, "cantidad": 2 },
        { "id_producto": 3, "cantidad": 1 }
    ]
}


### Actualizar estado de un pedido
PUT http://localhost:8000/api/pedidos1.php
Content-Type: application/json

{
    "id_pedido": 30,
    "estado": "En preparación"
}

### Eliminar un pedido
DELETE http://localhost:8000/api/pedidos1.php
Content-Type: application/json

{
    "id_pedido": 28
}
