### Registrar un usuario
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
  "nombre": "Lola",
  "email": "lola@example.com",
  "contrasenia": "lola",
  "rol": ""
}


###
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
    "nombre": "maria",
    "email": "maria@gmail.com",
    "contrasenia": "ana",
    "rol": ""
}

###
POST http://localhost:8000/api/register.php
Content-Type: application/json

{
    "nombre": "pepe",
    "email": "pepe@gmail.com",
    "contrasenia": "pepe",
    "rol": ""
}

###
POST http://localhost:8000/api/login.php
Content-Type: application/json

{
  
    "email": "maria@gmail.com",
    "contrasenia": "ana"
    
}

### INsertar un pedido
POST http://localhost:8000/api/pedidos.php
Content-Type: application/json

{  
  "productos": [
    { "id_producto": 1, "cantidad": 3 },
    { "id_producto": 2, "cantidad": 5 }
  ]
}

### Obtener los pedidos
GET http://localhost:8000/api/pedidos.php?num_empleado=3
Content-Type: application/json
